/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DeTodoSA;

import java.util.ArrayList;

/**
 *
 * @author Anitabonita
 */
public class DeTodo extends javax.swing.JFrame {

    public static ArrayList<String> listaCategoria = new ArrayList<>();

    /**
     * Creates new form DeTodo
     */
    public DeTodo() {
        initComponents();
        cargarCategorias();
    }

    public void cargarCategorias() {
        listaCategoria.add("Comestible");
        listaCategoria.add("Farmacia");
        listaCategoria.add("Electronica");
        listaCategoria.add("Ropa");
        listaCategoria.add("Limpieza");
        listaCategoria.add("Perfumeria");
        listaCategoria.add("Mascotas");
        listaCategoria.add("Panderia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuAdministracion = new javax.swing.JMenu();
        menuGestion = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jmItemNombre = new javax.swing.JMenuItem();
        jmItemPrecio = new javax.swing.JMenuItem();
        jmItemRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        jmenuAdministracion.setText("Administracion");

        menuGestion.setText("Gestion de Productos");
        menuGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGestionMouseClicked(evt);
            }
        });
        menuGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionActionPerformed(evt);
            }
        });
        jmenuAdministracion.add(menuGestion);

        jMenuBar1.add(jmenuAdministracion);

        jMenuConsultas.setText("Consultas");

        jmItemNombre.setText("Consulta por Nombre");
        jmItemNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemNombreActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jmItemNombre);

        jmItemPrecio.setText("Consulta por Precio");
        jMenuConsultas.add(jmItemPrecio);

        jmItemRubro.setText("Consulta por Rubro");
        jmItemRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemRubroActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jmItemRubro);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemNombreActionPerformed

    private void jmItemRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemRubroActionPerformed

    private void menuGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGestionMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_menuGestionMouseClicked

    private void menuGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
        escritorio.repaint();
        GestionDeProductos produ = new GestionDeProductos();
        produ.setLocation((escritorio.getWidth() - produ.getWidth()) / 2, (escritorio.getHeight() - produ.getHeight()) / 2);
        produ.setVisible(true);
        escritorio.add(produ);
        produ.toFront();
    }//GEN-LAST:event_menuGestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jmItemNombre;
    private javax.swing.JMenuItem jmItemPrecio;
    private javax.swing.JMenuItem jmItemRubro;
    private javax.swing.JMenu jmenuAdministracion;
    private javax.swing.JMenuItem menuGestion;
    // End of variables declaration//GEN-END:variables
}
